// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (owner_id, name)
VALUES ($1, $2)
RETURNING id
`

type CreateListParams struct {
	OwnerID string `db:"owner_id" json:"owner_id"`
	Name    string `db:"name" json:"name"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (int64, error) {
	row := q.db.QueryRow(ctx, createList, arg.OwnerID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists
WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const deleteLists = `-- name: DeleteLists :exec
DELETE FROM lists
WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteLists(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, deleteLists, ids)
	return err
}

const getList = `-- name: GetList :one
SELECT id, owner_id, name, created_at FROM lists
WHERE id = $1
`

func (q *Queries) GetList(ctx context.Context, id int64) (List, error) {
	row := q.db.QueryRow(ctx, getList, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getListAccess = `-- name: GetListAccess :one
SELECT user_id, list_id, can_read_tasks, can_update_tasks, can_create_tasks, can_delete_tasks FROM list_access
WHERE user_id = $1 AND list_id = $2
`

type GetListAccessParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ListID int64  `db:"list_id" json:"list_id"`
}

func (q *Queries) GetListAccess(ctx context.Context, arg GetListAccessParams) (ListAccess, error) {
	row := q.db.QueryRow(ctx, getListAccess, arg.UserID, arg.ListID)
	var i ListAccess
	err := row.Scan(
		&i.UserID,
		&i.ListID,
		&i.CanReadTasks,
		&i.CanUpdateTasks,
		&i.CanCreateTasks,
		&i.CanDeleteTasks,
	)
	return i, err
}

const getListWhere = `-- name: GetListWhere :one
SELECT id, owner_id, name, created_at FROM lists
WHERE $1
LIMIT 1
`

func (q *Queries) GetListWhere(ctx context.Context, filter pgtype.Bool) (List, error) {
	row := q.db.QueryRow(ctx, getListWhere, filter)
	var i List
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getLists = `-- name: GetLists :many
SELECT id, owner_id, name, created_at FROM lists
WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetLists(ctx context.Context, ids []int64) ([]List, error) {
	rows, err := q.db.Query(ctx, getLists, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsWhere = `-- name: GetListsWhere :many
SELECT id, owner_id, name, created_at FROM lists
WHERE $1
LIMIT $2
`

type GetListsWhereParams struct {
	Filter pgtype.Bool `db:"filter" json:"filter"`
	Count  int64       `db:"count" json:"count"`
}

func (q *Queries) GetListsWhere(ctx context.Context, arg GetListsWhereParams) ([]List, error) {
	rows, err := q.db.Query(ctx, getListsWhere, arg.Filter, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setListAccess = `-- name: SetListAccess :exec
INSERT INTO list_access (user_id, list_id, can_read_tasks, can_update_tasks, can_create_tasks, can_delete_tasks)
VALUES ($1, $2, $3, $4, $5, $6)

ON CONFLICT(user_id, list_id) DO

UPDATE SET can_read_tasks = EXCLUDED.can_read_tasks
    , can_update_tasks = EXCLUDED.can_update_tasks
    , can_create_tasks = EXCLUDED.can_create_tasks
    , can_delete_tasks = EXCLUDED.can_delete_tasks
`

type SetListAccessParams struct {
	UserID         string `db:"user_id" json:"user_id"`
	ListID         int64  `db:"list_id" json:"list_id"`
	CanReadTasks   bool   `db:"can_read_tasks" json:"can_read_tasks"`
	CanUpdateTasks bool   `db:"can_update_tasks" json:"can_update_tasks"`
	CanCreateTasks bool   `db:"can_create_tasks" json:"can_create_tasks"`
	CanDeleteTasks bool   `db:"can_delete_tasks" json:"can_delete_tasks"`
}

func (q *Queries) SetListAccess(ctx context.Context, arg SetListAccessParams) error {
	_, err := q.db.Exec(ctx, setListAccess,
		arg.UserID,
		arg.ListID,
		arg.CanReadTasks,
		arg.CanUpdateTasks,
		arg.CanCreateTasks,
		arg.CanDeleteTasks,
	)
	return err
}

const updateList = `-- name: UpdateList :exec
UPDATE lists SET
    owner_id = $1,
    name = $2
WHERE id = $3
`

type UpdateListParams struct {
	OwnerID string `db:"owner_id" json:"owner_id"`
	Name    string `db:"name" json:"name"`
	ID      int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) error {
	_, err := q.db.Exec(ctx, updateList, arg.OwnerID, arg.Name, arg.ID)
	return err
}

const updateLists = `-- name: UpdateLists :exec
UPDATE lists SET
    owner_id = $1,
    name = $2
WHERE id = ANY($3::bigint[])
`

type UpdateListsParams struct {
	OwnerID string  `db:"owner_id" json:"owner_id"`
	Name    string  `db:"name" json:"name"`
	Ids     []int64 `db:"ids" json:"ids"`
}

func (q *Queries) UpdateLists(ctx context.Context, arg UpdateListsParams) error {
	_, err := q.db.Exec(ctx, updateLists, arg.OwnerID, arg.Name, arg.Ids)
	return err
}
