// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListPermission = `-- name: CreateListPermission :exec
INSERT INTO list_permissions (
    user_id,
    list_id,
    can_read_tasks,
    can_update_tasks,
    can_create_tasks,
    can_delete_tasks
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateListPermissionParams struct {
	UserID         string      `db:"user_id" json:"user_id"`
	ListID         int64       `db:"list_id" json:"list_id"`
	CanReadTasks   pgtype.Bool `db:"can_read_tasks" json:"can_read_tasks"`
	CanUpdateTasks pgtype.Bool `db:"can_update_tasks" json:"can_update_tasks"`
	CanCreateTasks pgtype.Bool `db:"can_create_tasks" json:"can_create_tasks"`
	CanDeleteTasks pgtype.Bool `db:"can_delete_tasks" json:"can_delete_tasks"`
}

func (q *Queries) CreateListPermission(ctx context.Context, arg CreateListPermissionParams) error {
	_, err := q.db.Exec(ctx, createListPermission,
		arg.UserID,
		arg.ListID,
		arg.CanReadTasks,
		arg.CanUpdateTasks,
		arg.CanCreateTasks,
		arg.CanDeleteTasks,
	)
	return err
}

const deleteListPermission = `-- name: DeleteListPermission :exec
DELETE FROM list_permissions
WHERE user_id = $1 AND list_id = $2
`

type DeleteListPermissionParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ListID int64  `db:"list_id" json:"list_id"`
}

func (q *Queries) DeleteListPermission(ctx context.Context, arg DeleteListPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteListPermission, arg.UserID, arg.ListID)
	return err
}

const deleteListPermissions = `-- name: DeleteListPermissions :exec
DELETE FROM list_permissions
WHERE (user_id, list_id) IN (
    SELECT unnest($1::text[]), unnest($2::bigint[])
)
`

type DeleteListPermissionsParams struct {
	UserIds []string `db:"user_ids" json:"user_ids"`
	ListIds []int64  `db:"list_ids" json:"list_ids"`
}

func (q *Queries) DeleteListPermissions(ctx context.Context, arg DeleteListPermissionsParams) error {
	_, err := q.db.Exec(ctx, deleteListPermissions, arg.UserIds, arg.ListIds)
	return err
}

const getListPermission = `-- name: GetListPermission :one
SELECT user_id, list_id, can_read_tasks, can_update_tasks, can_create_tasks, can_delete_tasks FROM list_permissions
WHERE user_id = $1 AND list_id = $2
`

type GetListPermissionParams struct {
	UserID string `db:"user_id" json:"user_id"`
	ListID int64  `db:"list_id" json:"list_id"`
}

func (q *Queries) GetListPermission(ctx context.Context, arg GetListPermissionParams) (ListPermission, error) {
	row := q.db.QueryRow(ctx, getListPermission, arg.UserID, arg.ListID)
	var i ListPermission
	err := row.Scan(
		&i.UserID,
		&i.ListID,
		&i.CanReadTasks,
		&i.CanUpdateTasks,
		&i.CanCreateTasks,
		&i.CanDeleteTasks,
	)
	return i, err
}

const getListPermissionWhere = `-- name: GetListPermissionWhere :one
SELECT user_id, list_id, can_read_tasks, can_update_tasks, can_create_tasks, can_delete_tasks FROM list_permissions
WHERE $1
LIMIT 1
`

func (q *Queries) GetListPermissionWhere(ctx context.Context, filter pgtype.Bool) (ListPermission, error) {
	row := q.db.QueryRow(ctx, getListPermissionWhere, filter)
	var i ListPermission
	err := row.Scan(
		&i.UserID,
		&i.ListID,
		&i.CanReadTasks,
		&i.CanUpdateTasks,
		&i.CanCreateTasks,
		&i.CanDeleteTasks,
	)
	return i, err
}

const getListPermissions = `-- name: GetListPermissions :many
SELECT user_id, list_id, can_read_tasks, can_update_tasks, can_create_tasks, can_delete_tasks FROM list_permissions
WHERE (user_id, list_id) IN (
    SELECT unnest($1::text[]), unnest($2::bigint[])
)
`

type GetListPermissionsParams struct {
	UserIds []string `db:"user_ids" json:"user_ids"`
	ListIds []int64  `db:"list_ids" json:"list_ids"`
}

func (q *Queries) GetListPermissions(ctx context.Context, arg GetListPermissionsParams) ([]ListPermission, error) {
	rows, err := q.db.Query(ctx, getListPermissions, arg.UserIds, arg.ListIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermission
	for rows.Next() {
		var i ListPermission
		if err := rows.Scan(
			&i.UserID,
			&i.ListID,
			&i.CanReadTasks,
			&i.CanUpdateTasks,
			&i.CanCreateTasks,
			&i.CanDeleteTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListPermissionsWhere = `-- name: GetListPermissionsWhere :many
SELECT user_id, list_id, can_read_tasks, can_update_tasks, can_create_tasks, can_delete_tasks FROM list_permissions
WHERE $1
LIMIT $2
`

type GetListPermissionsWhereParams struct {
	Filter pgtype.Bool `db:"filter" json:"filter"`
	Count  int64       `db:"count" json:"count"`
}

func (q *Queries) GetListPermissionsWhere(ctx context.Context, arg GetListPermissionsWhereParams) ([]ListPermission, error) {
	rows, err := q.db.Query(ctx, getListPermissionsWhere, arg.Filter, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermission
	for rows.Next() {
		var i ListPermission
		if err := rows.Scan(
			&i.UserID,
			&i.ListID,
			&i.CanReadTasks,
			&i.CanUpdateTasks,
			&i.CanCreateTasks,
			&i.CanDeleteTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListPermission = `-- name: UpdateListPermission :exec
UPDATE list_permissions SET
    can_read_tasks   = $1,
    can_update_tasks = $2,
    can_create_tasks = $3,
    can_delete_tasks = $4
WHERE user_id = $5 AND list_id = $6
`

type UpdateListPermissionParams struct {
	CanReadTasks   pgtype.Bool `db:"can_read_tasks" json:"can_read_tasks"`
	CanUpdateTasks pgtype.Bool `db:"can_update_tasks" json:"can_update_tasks"`
	CanCreateTasks pgtype.Bool `db:"can_create_tasks" json:"can_create_tasks"`
	CanDeleteTasks pgtype.Bool `db:"can_delete_tasks" json:"can_delete_tasks"`
	UserID         string      `db:"user_id" json:"user_id"`
	ListID         int64       `db:"list_id" json:"list_id"`
}

func (q *Queries) UpdateListPermission(ctx context.Context, arg UpdateListPermissionParams) error {
	_, err := q.db.Exec(ctx, updateListPermission,
		arg.CanReadTasks,
		arg.CanUpdateTasks,
		arg.CanCreateTasks,
		arg.CanDeleteTasks,
		arg.UserID,
		arg.ListID,
	)
	return err
}

const updateListPermissions = `-- name: UpdateListPermissions :exec
UPDATE list_permissions SET
    can_read_tasks   = $1,
    can_update_tasks = $2,
    can_create_tasks = $3,
    can_delete_tasks = $4
WHERE (user_id, list_id) IN (
    SELECT unnest($5::text[]), unnest($6::bigint[])
)
`

type UpdateListPermissionsParams struct {
	CanReadTasks   pgtype.Bool `db:"can_read_tasks" json:"can_read_tasks"`
	CanUpdateTasks pgtype.Bool `db:"can_update_tasks" json:"can_update_tasks"`
	CanCreateTasks pgtype.Bool `db:"can_create_tasks" json:"can_create_tasks"`
	CanDeleteTasks pgtype.Bool `db:"can_delete_tasks" json:"can_delete_tasks"`
	UserIds        []string    `db:"user_ids" json:"user_ids"`
	ListIds        []int64     `db:"list_ids" json:"list_ids"`
}

func (q *Queries) UpdateListPermissions(ctx context.Context, arg UpdateListPermissionsParams) error {
	_, err := q.db.Exec(ctx, updateListPermissions,
		arg.CanReadTasks,
		arg.CanUpdateTasks,
		arg.CanCreateTasks,
		arg.CanDeleteTasks,
		arg.UserIds,
		arg.ListIds,
	)
	return err
}
