// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type List struct {
	ID        int64            `db:"id" json:"id"`
	OwnerID   pgtype.Text      `db:"owner_id" json:"owner_id"`
	Name      string           `db:"name" json:"name"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ListPermission struct {
	UserID         string      `db:"user_id" json:"user_id"`
	ListID         int64       `db:"list_id" json:"list_id"`
	CanReadTasks   pgtype.Bool `db:"can_read_tasks" json:"can_read_tasks"`
	CanUpdateTasks pgtype.Bool `db:"can_update_tasks" json:"can_update_tasks"`
	CanCreateTasks pgtype.Bool `db:"can_create_tasks" json:"can_create_tasks"`
	CanDeleteTasks pgtype.Bool `db:"can_delete_tasks" json:"can_delete_tasks"`
}

type Task struct {
	ID          int32            `db:"id" json:"id"`
	ListID      pgtype.Int8      `db:"list_id" json:"list_id"`
	Title       string           `db:"title" json:"title"`
	Description pgtype.Text      `db:"description" json:"description"`
	Priority    pgtype.Int4      `db:"priority" json:"priority"`
	DueDate     pgtype.Timestamp `db:"due_date" json:"due_date"`
	Assignee    pgtype.Text      `db:"assignee" json:"assignee"`
	Labels      []string         `db:"labels" json:"labels"`
}

type User struct {
	ID          string      `db:"id" json:"id"`
	FullName    string      `db:"full_name" json:"full_name"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Email       string      `db:"email" json:"email"`
}
