// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SecretScopes string

const (
	SecretScopesUserLogin SecretScopes = "user-login"
)

func (e *SecretScopes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SecretScopes(s)
	case string:
		*e = SecretScopes(s)
	default:
		return fmt.Errorf("unsupported scan type for SecretScopes: %T", src)
	}
	return nil
}

type NullSecretScopes struct {
	SecretScopes SecretScopes `json:"secret_scopes"`
	Valid        bool         `json:"valid"` // Valid is true if SecretScopes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSecretScopes) Scan(value interface{}) error {
	if value == nil {
		ns.SecretScopes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SecretScopes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSecretScopes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SecretScopes), nil
}

type List struct {
	ID        int64            `db:"id" json:"id"`
	OwnerID   string           `db:"owner_id" json:"owner_id"`
	Name      string           `db:"name" json:"name"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ListAccess struct {
	UserID         string `db:"user_id" json:"user_id"`
	ListID         int64  `db:"list_id" json:"list_id"`
	CanReadTasks   bool   `db:"can_read_tasks" json:"can_read_tasks"`
	CanUpdateTasks bool   `db:"can_update_tasks" json:"can_update_tasks"`
	CanCreateTasks bool   `db:"can_create_tasks" json:"can_create_tasks"`
	CanDeleteTasks bool   `db:"can_delete_tasks" json:"can_delete_tasks"`
}

type Secret struct {
	Key   string       `db:"key" json:"key"`
	Scope SecretScopes `db:"scope" json:"scope"`
	Value string       `db:"value" json:"value"`
}

type Task struct {
	ID          int64            `db:"id" json:"id"`
	ListID      int64            `db:"list_id" json:"list_id"`
	Title       string           `db:"title" json:"title"`
	Description pgtype.Text      `db:"description" json:"description"`
	Priority    pgtype.Int4      `db:"priority" json:"priority"`
	DueDate     pgtype.Timestamp `db:"due_date" json:"due_date"`
	Assignee    pgtype.Text      `db:"assignee" json:"assignee"`
	Labels      []string         `db:"labels" json:"labels"`
}

type User struct {
	ID          string      `db:"id" json:"id"`
	FullName    string      `db:"full_name" json:"full_name"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Email       string      `db:"email" json:"email"`
}
