// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secrets.sql

package sqlc

import (
	"context"
)

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (key, scope, value)
VALUES ($1, $2, $3)
`

type CreateSecretParams struct {
	Key   string       `db:"key" json:"key"`
	Scope SecretScopes `db:"scope" json:"scope"`
	Pass  string       `db:"pass" json:"pass"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.Exec(ctx, createSecret, arg.Key, arg.Scope, arg.Pass)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
UPDATE secrets
SET value = $1
WHERE key = $2 AND scope = $3
`

type DeleteSecretParams struct {
	Value string       `db:"value" json:"value"`
	Key   string       `db:"key" json:"key"`
	Scope SecretScopes `db:"scope" json:"scope"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.Exec(ctx, deleteSecret, arg.Value, arg.Key, arg.Scope)
	return err
}

const getSercert = `-- name: GetSercert :one
SELECT value
FROM secrets
WHERE key = $1 AND scope = $2
`

type GetSercertParams struct {
	Key   string       `db:"key" json:"key"`
	Scope SecretScopes `db:"scope" json:"scope"`
}

func (q *Queries) GetSercert(ctx context.Context, arg GetSercertParams) (string, error) {
	row := q.db.QueryRow(ctx, getSercert, arg.Key, arg.Scope)
	var value string
	err := row.Scan(&value)
	return value, err
}

const updateSecret = `-- name: UpdateSecret :exec
UPDATE secrets
SET value = $1
WHERE key = $2 AND scope = $3
`

type UpdateSecretParams struct {
	Value string       `db:"value" json:"value"`
	Key   string       `db:"key" json:"key"`
	Scope SecretScopes `db:"scope" json:"scope"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) error {
	_, err := q.db.Exec(ctx, updateSecret, arg.Value, arg.Key, arg.Scope)
	return err
}
