// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description, priority, due_date, assignee, labels, list_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateTaskParams struct {
	Title       string           `db:"title" json:"title"`
	Description pgtype.Text      `db:"description" json:"description"`
	Priority    pgtype.Int4      `db:"priority" json:"priority"`
	DueDate     pgtype.Timestamp `db:"due_date" json:"due_date"`
	Assignee    pgtype.Text      `db:"assignee" json:"assignee"`
	Labels      []string         `db:"labels" json:"labels"`
	ListID      pgtype.Int8      `db:"list_id" json:"list_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.Assignee,
		arg.Labels,
		arg.ListID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const deleteTasks = `-- name: DeleteTasks :exec
DELETE FROM tasks
WHERE id = ANY($1::int[])
`

func (q *Queries) DeleteTasks(ctx context.Context, ids []int32) error {
	_, err := q.db.Exec(ctx, deleteTasks, ids)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, list_id, title, description, priority, due_date, assignee, labels FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Assignee,
		&i.Labels,
	)
	return i, err
}

const getTaskWhere = `-- name: GetTaskWhere :one
SELECT id, list_id, title, description, priority, due_date, assignee, labels FROM tasks
WHERE $1
LIMIT 1
`

func (q *Queries) GetTaskWhere(ctx context.Context, filter pgtype.Bool) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskWhere, filter)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Assignee,
		&i.Labels,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT id, list_id, title, description, priority, due_date, assignee, labels FROM tasks
WHERE id = ANY($1::int[])
`

func (q *Queries) GetTasks(ctx context.Context, ids []int32) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasks, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Assignee,
			&i.Labels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksWhere = `-- name: GetTasksWhere :many
SELECT id, list_id, title, description, priority, due_date, assignee, labels FROM tasks
WHERE $1
LIMIT $2
`

type GetTasksWhereParams struct {
	Filter pgtype.Bool `db:"filter" json:"filter"`
	Count  int64       `db:"count" json:"count"`
}

func (q *Queries) GetTasksWhere(ctx context.Context, arg GetTasksWhereParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksWhere, arg.Filter, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Assignee,
			&i.Labels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET
    title = $1,
    description = $2,
    priority = $3,
    due_date = $4,
    assignee = $5,
    labels = $6,
    list_id = $7
WHERE id = $8
`

type UpdateTaskParams struct {
	Title       string           `db:"title" json:"title"`
	Description pgtype.Text      `db:"description" json:"description"`
	Priority    pgtype.Int4      `db:"priority" json:"priority"`
	DueDate     pgtype.Timestamp `db:"due_date" json:"due_date"`
	Assignee    pgtype.Text      `db:"assignee" json:"assignee"`
	Labels      []string         `db:"labels" json:"labels"`
	ListID      pgtype.Int8      `db:"list_id" json:"list_id"`
	ID          int32            `db:"id" json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.Assignee,
		arg.Labels,
		arg.ListID,
		arg.ID,
	)
	return err
}

const updateTasks = `-- name: UpdateTasks :exec
UPDATE tasks SET
    title = $1,
    description = $2,
    priority = $3,
    due_date = $4,
    assignee = $5,
    labels = $6,
    list_id = $7
WHERE id = ANY($8::int[])
`

type UpdateTasksParams struct {
	Title       string           `db:"title" json:"title"`
	Description pgtype.Text      `db:"description" json:"description"`
	Priority    pgtype.Int4      `db:"priority" json:"priority"`
	DueDate     pgtype.Timestamp `db:"due_date" json:"due_date"`
	Assignee    pgtype.Text      `db:"assignee" json:"assignee"`
	Labels      []string         `db:"labels" json:"labels"`
	ListID      pgtype.Int8      `db:"list_id" json:"list_id"`
	Ids         []int32          `db:"ids" json:"ids"`
}

func (q *Queries) UpdateTasks(ctx context.Context, arg UpdateTasksParams) error {
	_, err := q.db.Exec(ctx, updateTasks,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.Assignee,
		arg.Labels,
		arg.ListID,
		arg.Ids,
	)
	return err
}
