// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    full_name,
    display_name,
    email
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateUserParams struct {
	ID          string      `db:"id" json:"id"`
	FullName    string      `db:"full_name" json:"full_name"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Email       string      `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.DisplayName,
		arg.Email,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteUsers(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, deleteUsers, ids)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, display_name, email FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const getUserWhere = `-- name: GetUserWhere :one
SELECT id, full_name, display_name, email FROM users
WHERE $1
LIMIT 1
`

func (q *Queries) GetUserWhere(ctx context.Context, filter pgtype.Bool) (User, error) {
	row := q.db.QueryRow(ctx, getUserWhere, filter)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, full_name, display_name, email FROM users
WHERE id = ANY($1::text[])
`

func (q *Queries) GetUsers(ctx context.Context, ids []string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhere = `-- name: GetUsersWhere :many
SELECT id, full_name, display_name, email FROM users
WHERE $1
LIMIT $2
`

type GetUsersWhereParams struct {
	Filter pgtype.Bool `db:"filter" json:"filter"`
	Count  int64       `db:"count" json:"count"`
}

func (q *Queries) GetUsersWhere(ctx context.Context, arg GetUsersWhereParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersWhere, arg.Filter, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    full_name = $1,
    display_name = $2,
    email = $3
WHERE id = $4
`

type UpdateUserParams struct {
	FullName    string      `db:"full_name" json:"full_name"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Email       string      `db:"email" json:"email"`
	ID          string      `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.FullName,
		arg.DisplayName,
		arg.Email,
		arg.ID,
	)
	return err
}

const updateUsers = `-- name: UpdateUsers :exec
UPDATE users SET
    full_name = $1,
    display_name = $2,
    email = $3
WHERE id = ANY($4::text[])
`

type UpdateUsersParams struct {
	FullName    string      `db:"full_name" json:"full_name"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Email       string      `db:"email" json:"email"`
	Ids         []string    `db:"ids" json:"ids"`
}

func (q *Queries) UpdateUsers(ctx context.Context, arg UpdateUsersParams) error {
	_, err := q.db.Exec(ctx, updateUsers,
		arg.FullName,
		arg.DisplayName,
		arg.Email,
		arg.Ids,
	)
	return err
}
