services:
  server:
    image: mcr.microsoft.com/vscode/devcontainers/go:1.24-bookworm
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://devuser:devpass@database:5432/devdb?sslmode=disable
    command: sleep infinity

  database:
    image: docker.io/postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
